services:
  app:
    build:
      context: .
    entrypoint: ["/www/development.sh"]
    ports:
      - "${APP_PORT:-8080}:80"
    env_file:
      - .env
    environment:
      APP_PORT: 80
      DB_HOST: "${DB_HOST:-db}"
    networks:
      - app_network
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: "${DB_USERNAME:-postgres}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-}"
      POSTGRES_DB: "${DB_DATABASE:-go_api_cms}"
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    restart: always

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
